from .. import Availability, Class, Constant, Define, Method, Parameter, Type

gx_class = Class('STK',
                 doc="""
                 The :class:`STK` class is used for plotting a single data profile in
                 an :class:`MVIEW`. The :class:`MSTK` class (see :class:`MSTK`) is used to plot
                 multiple :class:`STK` objects to a single map.
                 
                 Use :func:`AddSTK_MSTK` fuction to create a :class:`STK` object before
                 using functions in this file
                 
                 SEE :class:`MSTK` FILE FOR DETAILED DESCRIPTIONS OF ALL FUNCTION PARAMETERS.
                 """)


gx_defines = [
    Define('STK_AXIS',
           doc=":class:`STK` Axis defines",
           constants=[
               Constant('STK_AXIS_X', value='0', type=Type.INT32_T,
                        doc="X Axis")                        ,
               Constant('STK_AXIS_Y', value='1', type=Type.INT32_T,
                        doc="Y Axis")                        
           ]),

    Define('STK_FLAG',
           doc="Stack flags",
           constants=[
               Constant('STK_FLAG_PROFILE', value='0', type=Type.INT32_T)                        ,
               Constant('STK_FLAG_FID', value='1', type=Type.INT32_T)                        ,
               Constant('STK_FLAG_SYMBOL', value='2', type=Type.INT32_T)                        ,
               Constant('STK_FLAG_XBAR', value='3', type=Type.INT32_T)                        ,
               Constant('STK_FLAG_XLABEL', value='4', type=Type.INT32_T)                        ,
               Constant('STK_FLAG_XTITLE', value='5', type=Type.INT32_T)                        ,
               Constant('STK_FLAG_YBAR', value='6', type=Type.INT32_T)                        ,
               Constant('STK_FLAG_YLABEL', value='7', type=Type.INT32_T)                        ,
               Constant('STK_FLAG_YTITLE', value='8', type=Type.INT32_T)                        ,
               Constant('STK_FLAG_GRID1', value='9', type=Type.INT32_T)                        ,
               Constant('STK_FLAG_GRID2', value='10', type=Type.INT32_T)                        
           ]),

    Define('STK_GRID',
           doc="Stack Grid define",
           constants=[
               Constant('STK_GRID_PRIMARY', value='0', type=Type.INT32_T,
                        doc="Primary Grid")                        ,
               Constant('STK_GRID_SECONDARY', value='1', type=Type.INT32_T,
                        doc="Secondary Grid")                        
           ])]


gx_methods = {
    'Miscellaneous': [

        Method('GetTransParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Get transformation parameters in :class:`STK` object",
               notes="""
               See above full description of each parameters
               :class:`VV`'s for X channel transformation can be NULL if the
               transformation is log or loglinear. The same for Y channel.
               
               See :class:`MSTK` for detailed description of all function parameters
               """,
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T, is_ref=True,
                             doc="Type of transformation for horizontal axis"),
                   Parameter('p3', type=Type.DOUBLE, is_ref=True,
                             doc="Minimum value to apply logarithmic"),
                   Parameter('p4', type="VV",
                             doc="Comma separated parameters defining linear compress data range"),
                   Parameter('p5', type="VV",
                             doc="Comma separated parameters defining scaling factors for"),
                   Parameter('p6', type=Type.INT32_T, is_ref=True,
                             doc="Type of scaling for vertical axis"),
                   Parameter('p7', type=Type.DOUBLE, is_ref=True,
                             doc="Minimum value to apply logarithmic"),
                   Parameter('p8', type="VV",
                             doc="Comma separated parameters defining linear compress data range"),
                   Parameter('p9', type="VV",
                             doc="Comma separated parameters defining scaling factors for")
               ]),

        Method('iGetAxisFormat_STK', module='geogxx', version='5.1.5',
               availability=Availability.LICENSED, 
               doc="Get axis number display format.",
               notes="By default, :def_val:`DB_CHAN_FORMAT_NORMAL`",
               return_type=Type.INT32_T,
               return_doc="The current format - :def:`DB_CHAN_FORMAT`",
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T,
                             doc=":def:`STK_AXIS`")
               ]),

        Method('IGetAxisParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Get parameters in :class:`STK` object relating drawing X/Y axis",
               notes="""
               See :class:`MSTK` for detailed description of all function parameters
               ? mark in the note represent either X and Y
               """,
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T, is_ref=True,
                             doc="?BARDRAW: Bottom and/or Top, or Left and/or Right"),
                   Parameter('p3', type=Type.DOUBLE, is_ref=True,
                             doc="Bottom Y/Left X location"),
                   Parameter('p4', type=Type.DOUBLE, is_ref=True,
                             doc="Top Y/Right X location"),
                   Parameter('p5', type=Type.DOUBLE, is_ref=True,
                             doc="?BARLINETHICK  - Line thickness in mm. Default is 0.05"),
                   Parameter('p6', type=Type.STRING, is_ref=True, size_of_param='6',
                             doc="?BARCOLOR      - Line color string in RGB model. Default is black"),
                   Parameter('p7', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Color string length"),
                   Parameter('p8', type=Type.DOUBLE, is_ref=True,
                             doc="?BARTICKINTEERVAL"),
                   Parameter('p9', type=Type.DOUBLE, is_ref=True,
                             doc="Major tick size in mm for bottom/left axis bar."),
                   Parameter('p10', type=Type.DOUBLE, is_ref=True,
                             doc="Major tick size in mm for top/right axis bar."),
                   Parameter('p11', type=Type.INT32_T, is_ref=True,
                             doc="?BARMINORTICK  - Number of minor ticks. (0) none, (-1) automatic"),
                   Parameter('p12', type=Type.INT32_T,
                             doc=":def:`STK_AXIS`")
               ]),

        Method('IGetFidParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Get parameters in :class:`STK` object relating drawing fid ticks",
               notes="See :class:`MSTK` for detailed description of all function parameters",
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.DOUBLE, is_ref=True,
                             doc="Y location in data unit to draw Fid ticks. Default is the bottom of the stack"),
                   Parameter('p3', type=Type.DOUBLE, is_ref=True,
                             doc="Fid tick size in mm. Default is 2.0mm"),
                   Parameter('p4', type=Type.DOUBLE, is_ref=True,
                             doc="Fid interval to draw ticks. Nice number is calculated by default"),
                   Parameter('p5', type=Type.STRING, is_ref=True, size_of_param='5',
                             doc="Font to use to label fids. Default is use 'default' font set in Montaj"),
                   Parameter('p6', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Font name string size"),
                   Parameter('p7', type=Type.DOUBLE, is_ref=True,
                             doc="Text size in mm to label fids. Default is 5mm"),
                   Parameter('p8', type=Type.STRING, is_ref=True, size_of_param='8',
                             doc="Text color string in RGB model. Default is black"),
                   Parameter('p9', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Text color string size")
               ]),

        Method('iGetFlag_STK', module='geogxx', version='6.0.1',
               availability=Availability.LICENSED, 
               doc="Get flag indicating part of :class:`STK` object is to be drawn or not",
               return_type=Type.INT32_T,
               return_doc="""
               FALSE (0) if part of the object is not to be drawn
               TRUE  (1) if part of the object is drawn
               """,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK`,"),
                   Parameter('p2', type=Type.INT32_T,
                             doc=":def:`STK_FLAG`")
               ]),

        Method('IGetGenParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Get general parameters in :class:`STK` object",
               notes="See :class:`MSTK` for detailed description of all function parameters",
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.STRING, is_ref=True, size_of_param='2',
                             doc="X channel name, REQUIRED"),
                   Parameter('p3', type=Type.INT32_T, default_length='STR_DB_SYMBOL',
                             doc="X channel name string length"),
                   Parameter('p4', type=Type.STRING, is_ref=True, size_of_param='4',
                             doc="Y channel name, REQUIRED"),
                   Parameter('p5', type=Type.INT32_T, default_length='STR_DB_SYMBOL',
                             doc="Y channel name string length"),
                   Parameter('p6', type=Type.STRING, is_ref=True, size_of_param='6',
                             doc="Group name"),
                   Parameter('p7', type=Type.INT32_T, default_length='STR_GROUP',
                             doc="Group name string length"),
                   Parameter('p8', type=Type.DOUBLE, is_ref=True,
                             doc="X scale (map scale, units/metre), REQUIRED"),
                   Parameter('p9', type=Type.DOUBLE, is_ref=True,
                             doc="Y scale (plot scale, units/mm), REQUIRED"),
                   Parameter('p10', type=Type.DOUBLE, is_ref=True,
                             doc="Minimum X value (data unit) to draw"),
                   Parameter('p11', type=Type.DOUBLE, is_ref=True,
                             doc="Maximum X value (data unit) to draw"),
                   Parameter('p12', type=Type.DOUBLE, is_ref=True,
                             doc="Minimum Y value (data unit) to draw"),
                   Parameter('p13', type=Type.DOUBLE, is_ref=True,
                             doc="Minimum horizontal location in mm of the stack on the map"),
                   Parameter('p14', type=Type.DOUBLE, is_ref=True,
                             doc="Minimum vertical location in mm on the map"),
                   Parameter('p15', type=Type.DOUBLE, is_ref=True,
                             doc="Profile height in mm on the map, must be > 0.0")
               ]),

        Method('IGetGridParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Get background grid parameters in :class:`STK` object",
               notes="""
               See :class:`MSTK` for detailed description of all function parameters
               ? mark in the note represent either X and Y
               """,
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T, is_ref=True,
                             doc="Type of grid to draw:"),
                   Parameter('p3', type=Type.DOUBLE, is_ref=True,
                             doc="Minimum X in ground unit to draw grid"),
                   Parameter('p4', type=Type.DOUBLE, is_ref=True,
                             doc="Maximum X in ground unit to draw grid"),
                   Parameter('p5', type=Type.DOUBLE, is_ref=True,
                             doc="Minimum Y in ground unit to draw grid"),
                   Parameter('p6', type=Type.DOUBLE, is_ref=True,
                             doc="Maximum Y in ground unit to draw grid"),
                   Parameter('p7', type=Type.DOUBLE, is_ref=True,
                             doc="Line thickness in mm. Default is 0.01mm"),
                   Parameter('p8', type=Type.DOUBLE, is_ref=True,
                             doc="Cross size or separation between dots in mm."),
                   Parameter('p9', type=Type.DOUBLE, is_ref=True,
                             doc="Separation between vertical grid lines."),
                   Parameter('p10', type=Type.DOUBLE, is_ref=True,
                             doc="Separation between horizontal grid lines."),
                   Parameter('p11', type=Type.STRING, is_ref=True, size_of_param='11',
                             doc="Grid line color string in RGB model. Default is black"),
                   Parameter('p12', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Color string length"),
                   Parameter('p13', type=Type.INT32_T,
                             doc=":def:`STK_GRID`")
               ]),

        Method('IGetLabelParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Get parameters in :class:`STK` object relating X/Y axis labels",
               notes="""
               See :class:`MSTK` for detailed description of all function parameters
               ? mark in the note represent either X and Y
               Sets the label format to GSF_NORMAL. To override this,
               use the :func:`SetAxisFormat_STK` function AFTER calling this.
               """,
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T, is_ref=True,
                             doc="Which axes to draw: Bottom/Top or Left/Right axes"),
                   Parameter('p3', type=Type.DOUBLE, is_ref=True,
                             doc="Bottom or Left axis label location"),
                   Parameter('p4', type=Type.INT32_T, is_ref=True,
                             doc="Bottom or Left labels orientation."),
                   Parameter('p5', type=Type.DOUBLE, is_ref=True,
                             doc="Top or Right axis label location"),
                   Parameter('p6', type=Type.INT32_T, is_ref=True,
                             doc="Top or Right axis label orientation"),
                   Parameter('p7', type=Type.DOUBLE, is_ref=True,
                             doc="Label interval. Default is to use related axis tick interval"),
                   Parameter('p8', type=Type.STRING, is_ref=True, size_of_param='8',
                             doc="Font to use to label. Default is use 'default' font set in Montaj"),
                   Parameter('p9', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Font name string size"),
                   Parameter('p10', type=Type.DOUBLE, is_ref=True,
                             doc="Text size in mm to draw profile labels. Default is 5mm"),
                   Parameter('p11', type=Type.STRING, is_ref=True, size_of_param='11',
                             doc="Text color string in RGB model. Default is black"),
                   Parameter('p12', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Color string size"),
                   Parameter('p13', type=Type.INT32_T, is_ref=True,
                             doc="?LABELBOUND    - Edge bound.  0 - No"),
                   Parameter('p14', type=Type.INT32_T,
                             doc=":def:`STK_AXIS`")
               ]),

        Method('IGetProfile_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Get profile parameters in :class:`STK` object",
               notes="See :class:`MSTK` for detailed description of all function parameters",
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T, is_ref=True,
                             doc="Profile line type.    1 - solid (default)"),
                   Parameter('p3', type=Type.DOUBLE, is_ref=True,
                             doc="Patterned line pitch in mm. Default is 10 mm"),
                   Parameter('p4', type=Type.DOUBLE, is_ref=True,
                             doc="Line thickness in mm. Default is 0.05mm"),
                   Parameter('p5', type=Type.STRING, is_ref=True, size_of_param='5',
                             doc="Color string in RGB model. Default is black"),
                   Parameter('p6', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Color string length"),
                   Parameter('p7', type=Type.INT32_T, is_ref=True,
                             doc="Wrap option"),
                   Parameter('p8', type=Type.INT32_T, is_ref=True,
                             doc="Clip option"),
                   Parameter('p9', type=Type.INT32_T, is_ref=True,
                             doc="Plot smoothed polyline."),
                   Parameter('p10', type="VV",
                             doc="Only use for :class:`VA` channels. NULL is acceptable which means all profiles in the :class:`VA` are plotted. :class:`VV` type of INT (integer)"),
                   Parameter('p11', type=Type.STRING, is_ref=True, size_of_param='11',
                             doc="Characters string to label profiles"),
                   Parameter('p12', type=Type.INT32_T, default_length='STR_DEFAULT',
                             doc="Label string length"),
                   Parameter('p13', type=Type.INT32_T, is_ref=True,
                             doc="Reference location to draw label."),
                   Parameter('p14', type=Type.STRING, is_ref=True, size_of_param='14',
                             doc="Font to use to draw profile labels. Default is use 'default' font set in Montaj"),
                   Parameter('p15', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Font name string length"),
                   Parameter('p16', type=Type.DOUBLE, is_ref=True,
                             doc="Text size in mm to draw profile labels. Default is 5mm"),
                   Parameter('p17', type=Type.STRING, is_ref=True, size_of_param='17',
                             doc="Text color string in RGB model. Default is black"),
                   Parameter('p18', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Color string length"),
                   Parameter('p19', type=Type.INT32_T, is_ref=True,
                             doc="Include :class:`VA` column numbers as part of the profile label 0 - no, 1 - yes")
               ]),

        Method('IGetProfileEx_STK', module='geogxx', version='5.0.3',
               availability=Availability.LICENSED, 
               doc="Get profile parameters in :class:`STK` object (added Break on dummy option)",
               notes="See :class:`MSTK` for detailed description of all function parameters",
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T, is_ref=True,
                             doc="Profile line type.    1 - solid (default)"),
                   Parameter('p3', type=Type.DOUBLE, is_ref=True,
                             doc="Patterned line pitch in mm. Default is 10 mm"),
                   Parameter('p4', type=Type.DOUBLE, is_ref=True,
                             doc="Line thickness in mm. Default is 0.05mm"),
                   Parameter('p5', type=Type.STRING, is_ref=True, size_of_param='5',
                             doc="Color string in RGB model. Default is black"),
                   Parameter('p6', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Color string length"),
                   Parameter('p7', type=Type.INT32_T, is_ref=True,
                             doc="Break on dummy option"),
                   Parameter('p8', type=Type.INT32_T, is_ref=True,
                             doc="Wrap option"),
                   Parameter('p9', type=Type.INT32_T, is_ref=True,
                             doc="Clip option"),
                   Parameter('p10', type=Type.INT32_T, is_ref=True,
                             doc="Plot smoothed polyline."),
                   Parameter('p11', type="VV",
                             doc="Only use for :class:`VA` channels. NULL is acceptable which means all profiles in the :class:`VA` are plotted. :class:`VV` type of INT (integer)"),
                   Parameter('p12', type=Type.STRING, is_ref=True, size_of_param='12',
                             doc="Characters string to label profiles"),
                   Parameter('p13', type=Type.INT32_T, default_length='STR_DEFAULT',
                             doc="Label string length"),
                   Parameter('p14', type=Type.INT32_T, is_ref=True,
                             doc="Reference location to draw label."),
                   Parameter('p15', type=Type.STRING, is_ref=True, size_of_param='15',
                             doc="Font to use to draw profile labels. Default is use 'default' font set in Montaj"),
                   Parameter('p16', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Font name string length"),
                   Parameter('p17', type=Type.DOUBLE, is_ref=True,
                             doc="Text size in mm to draw profile labels. Default is 5mm"),
                   Parameter('p18', type=Type.STRING, is_ref=True, size_of_param='18',
                             doc="Text color string in RGB model. Default is black"),
                   Parameter('p19', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Color string length"),
                   Parameter('p20', type=Type.INT32_T, is_ref=True,
                             doc="Include :class:`VA` column numbers as part of the profile label 0 - no, 1 - yes")
               ]),

        Method('IGetSymbParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Get parameters in :class:`STK` object relating drawing symbols",
               notes="See :class:`MSTK` for detailed description of all function parameters",
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.STRING, is_ref=True, size_of_param='2',
                             doc="Font to use to draw symbols. Default is use 'symbols.gfn' font"),
                   Parameter('p3', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Symbol font name string size"),
                   Parameter('p4', type=Type.DOUBLE, is_ref=True,
                             doc="Symbol size in mm. Default is 5mm"),
                   Parameter('p5', type=Type.STRING, is_ref=True, size_of_param='5',
                             doc="Edge color string in RGB model. Default is black"),
                   Parameter('p6', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Line color string size"),
                   Parameter('p7', type=Type.STRING, is_ref=True, size_of_param='7',
                             doc="Fill color string in RGB model. Default is black"),
                   Parameter('p8', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Fill color string size"),
                   Parameter('p9', type=Type.INT32_T, is_ref=True,
                             doc="Wrap option"),
                   Parameter('p10', type=Type.INT32_T, is_ref=True,
                             doc="Clip option"),
                   Parameter('p11', type=Type.DOUBLE, is_ref=True,
                             doc="Y location to draw symbols. Default is to use the data from Y channel"),
                   Parameter('p12', type=Type.INT32_T, is_ref=True,
                             doc="Number of levels to draw symbols"),
                   Parameter('p13', type="VV",
                             doc="Y values to define data ranges for each symbol types Type of REAL"),
                   Parameter('p14', type="VV",
                             doc="Symbol numbers (given in the symbol font) to draw, default is 20 TYPE of INT"),
                   Parameter('p15', type=Type.INT32_T, is_ref=True,
                             doc="Draw symbols ID (1) or not (0)"),
                   Parameter('p16', type=Type.STRING, is_ref=True, size_of_param='16',
                             doc="Font to use to draw symbol ID (A,B,C...). Default is use 'default'"),
                   Parameter('p17', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Text font name string size"),
                   Parameter('p18', type=Type.DOUBLE, is_ref=True,
                             doc="Text size in mm to draw profile labels. Default is 5mm"),
                   Parameter('p19', type=Type.STRING, is_ref=True, size_of_param='19',
                             doc="Text color string in RGB model. Default is black"),
                   Parameter('p20', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Text color string size")
               ]),

        Method('IGetTitleParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Get parameters in :class:`STK` object relating X/Y axis titles",
               notes="""
               See :class:`MSTK` for detailed description of all function parameters
               ? mark in the note represent either X and Y
               """,
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.STRING, is_ref=True, size_of_param='2',
                             doc="Title for bottom X axis/left Y axis. Default is no title."),
                   Parameter('p3', type=Type.INT32_T, default_length='STR_DEFAULT',
                             doc="Title string length"),
                   Parameter('p4', type=Type.STRING, is_ref=True, size_of_param='4',
                             doc="Title for top X axis/right Y axis. Default is no title."),
                   Parameter('p5', type=Type.INT32_T, default_length='STR_DEFAULT',
                             doc="Title string length"),
                   Parameter('p6', type=Type.INT32_T, is_ref=True,
                             doc="Bottom/Left axis title orientation."),
                   Parameter('p7', type=Type.DOUBLE, is_ref=True,
                             doc="X location to draw bottom/left axis title"),
                   Parameter('p8', type=Type.DOUBLE, is_ref=True,
                             doc="Y location to draw bottom/left axis title"),
                   Parameter('p9', type=Type.INT32_T, is_ref=True,
                             doc="Top/Right axis title orientation."),
                   Parameter('p10', type=Type.DOUBLE, is_ref=True,
                             doc="X location to draw top/right axis title"),
                   Parameter('p11', type=Type.DOUBLE, is_ref=True,
                             doc="Y location to draw top/right axis title"),
                   Parameter('p12', type=Type.STRING, is_ref=True, size_of_param='12',
                             doc="Font to draw titles. Default is use 'default' font set in Montaj"),
                   Parameter('p13', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Font name string length"),
                   Parameter('p14', type=Type.DOUBLE, is_ref=True,
                             doc="Text size in mm to draw titles. Default is 5mm"),
                   Parameter('p15', type=Type.STRING, is_ref=True, size_of_param='15',
                             doc="Text color string in RGB model. Default is black"),
                   Parameter('p16', type=Type.INT32_T, default_length='STR_DEFAULT_SHORT',
                             doc="Color string length"),
                   Parameter('p17', type=Type.INT32_T,
                             doc=":def:`STK_AXIS`")
               ]),

        Method('ISetFlag_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Set flag indicating part of :class:`STK` object is to be drawn or not",
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK`,"),
                   Parameter('p2', type=Type.INT32_T,
                             doc="Flag to set (0 or 1)"),
                   Parameter('p3', type=Type.INT32_T,
                             doc=":def:`STK_FLAG`")
               ]),

        Method('SetArrayColors_STK', module='geogxx', version='5.0.1',
               availability=Availability.LICENSED, 
               doc="Set colours for individual channels in a :class:`VA`, via an :class:`ITR`",
               notes="""
               The :class:`ITR` is consulted by taking the channel index and dividing
               by the number of channels; hence the :class:`ITR` maximum values should
               be in the range: 0 > values >= 1.0.
               """,
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK`,"),
                   Parameter('p2', type="ITR",
                             doc=":class:`ITR` object for colours")
               ]),

        Method('SetAxisFormat_STK', module='geogxx', version='5.1.5',
               availability=Availability.LICENSED, 
               doc="Set axis number display format.",
               notes="""
               By default, :def_val:`DB_CHAN_FORMAT_NORMAL` is used to display the values,
               or for values > 1.e7, :def_val:`DB_CHAN_FORMAT_EXP`.
               """,
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T,
                             doc=":def:`DB_CHAN_FORMAT`"),
                   Parameter('p3', type=Type.INT32_T,
                             doc=":def:`STK_AXIS`")
               ]),

        Method('SetAxisParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Set parameters in :class:`STK` object relating drawing X/Y axis",
               notes="""
               See :class:`MSTK` for detailed description of all function parameters
               ? mark in the note represent either X and Y
               """,
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T,
                             doc="?BARDRAW"),
                   Parameter('p3', type=Type.DOUBLE,
                             doc="Bottom Y/Left X location"),
                   Parameter('p4', type=Type.DOUBLE,
                             doc="Top Y/Right X location"),
                   Parameter('p5', type=Type.DOUBLE,
                             doc="?BARLINETHICK  - Line thickness in mm. Default is 0.05"),
                   Parameter('p6', type=Type.STRING,
                             doc="?BARCOLOR      - Line color string in RGB model. Default is black"),
                   Parameter('p7', type=Type.DOUBLE,
                             doc="?BARTICKINTEERVAL"),
                   Parameter('p8', type=Type.DOUBLE,
                             doc="Major tick size in mm for bottom/left axis bar."),
                   Parameter('p9', type=Type.DOUBLE,
                             doc="Major tick size in mm for top/right axis bar."),
                   Parameter('p10', type=Type.INT32_T,
                             doc="?BARMINORTICK  - Number of minor ticks. (0) none, (-1) automatic"),
                   Parameter('p11', type=Type.INT32_T,
                             doc=":def:`STK_AXIS`")
               ]),

        Method('SetFidParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Set parameters in :class:`STK` object relating drawing fid ticks",
               notes="See :class:`MSTK` for detailed description of all function parameters",
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.DOUBLE,
                             doc="Y location in data unit to draw Fid ticks. Default is the bottom of the stack"),
                   Parameter('p3', type=Type.DOUBLE,
                             doc="Fid tick size in mm. Default is 2.0mm"),
                   Parameter('p4', type=Type.DOUBLE,
                             doc="Fid interval to draw ticks. Nice number is calculated by default"),
                   Parameter('p5', type=Type.STRING,
                             doc="Font to use to label fids. Default is use 'default' font set in Montaj"),
                   Parameter('p6', type=Type.DOUBLE,
                             doc="Text size in mm to label fids. Default is 5mm"),
                   Parameter('p7', type=Type.STRING,
                             doc="Text color string in RGB model. Default is black")
               ]),

        Method('SetGenParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Set general parameters in :class:`STK` object",
               notes="See :class:`MSTK` for detailed description of all function parameters",
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.STRING,
                             doc="X channel name, REQUIRED"),
                   Parameter('p3', type=Type.STRING,
                             doc="Y channel name, REQUIRED"),
                   Parameter('p4', type=Type.STRING,
                             doc="Group name"),
                   Parameter('p5', type=Type.DOUBLE,
                             doc="X scale (map scale, units/metre), REQUIRED"),
                   Parameter('p6', type=Type.DOUBLE,
                             doc="Y scale (plot scale, units/mm), REQUIRED"),
                   Parameter('p7', type=Type.DOUBLE,
                             doc="Minimum X value (data unit) to draw"),
                   Parameter('p8', type=Type.DOUBLE,
                             doc="Maximum X value (data unit) to draw"),
                   Parameter('p9', type=Type.DOUBLE,
                             doc="Minimum Y value (data unit) to draw"),
                   Parameter('p10', type=Type.DOUBLE,
                             doc="Minimum horizontal location in mm of the stack on the map"),
                   Parameter('p11', type=Type.DOUBLE,
                             doc="Minimum vertical location in mm on the map"),
                   Parameter('p12', type=Type.DOUBLE,
                             doc="Profile height in mm on the map, must be > 0.0")
               ]),

        Method('SetGridParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Set background grid parameters in :class:`STK` object",
               notes="""
               See :class:`MSTK` for detailed description of all function parameters
               ? mark in the note represent either X and Y
               """,
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T,
                             doc="Type of grid to draw:"),
                   Parameter('p3', type=Type.DOUBLE,
                             doc="Minimum X in ground unit to draw grid"),
                   Parameter('p4', type=Type.DOUBLE,
                             doc="Maximum X in ground unit to draw grid"),
                   Parameter('p5', type=Type.DOUBLE,
                             doc="Minimum Y in ground unit to draw grid"),
                   Parameter('p6', type=Type.DOUBLE,
                             doc="Maximum Y in ground unit to draw grid"),
                   Parameter('p7', type=Type.DOUBLE,
                             doc="Line thickness in mm. Default is 0.01mm"),
                   Parameter('p8', type=Type.DOUBLE,
                             doc="Cross size or separation between dots in mm."),
                   Parameter('p9', type=Type.DOUBLE,
                             doc="Separation between vertical grid lines."),
                   Parameter('p10', type=Type.DOUBLE,
                             doc="Separation between horizontal grid lines."),
                   Parameter('p11', type=Type.STRING,
                             doc="Grid line color string in RGB model. Default is black"),
                   Parameter('p12', type=Type.INT32_T,
                             doc=":def:`STK_GRID`")
               ]),

        Method('SetLabelParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Set parameters in :class:`STK` object relating X/Y axis labels",
               notes="""
               See :class:`MSTK` for detailed description of all function parameters
               ? mark in the note represent either X and Y
               Sets the label format to GSF_NORMAL. To override this,
               use the :func:`SetAxisFormat_STK` function AFTER calling this.
               """,
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T,
                             doc="Bottom/Top or Left/Right axes"),
                   Parameter('p3', type=Type.DOUBLE,
                             doc="Bottom or Left axis label location"),
                   Parameter('p4', type=Type.INT32_T,
                             doc="Bottom or Left labels orientation."),
                   Parameter('p5', type=Type.DOUBLE,
                             doc="Top or Right axis label location"),
                   Parameter('p6', type=Type.INT32_T,
                             doc="Top or Right axis label orientation"),
                   Parameter('p7', type=Type.DOUBLE,
                             doc="Label interval. Default is to use related axis tick interval"),
                   Parameter('p8', type=Type.STRING,
                             doc="Font to use to label. Default is use 'default' font set in Montaj"),
                   Parameter('p9', type=Type.DOUBLE,
                             doc="Text size in mm to draw profile labels. Default is 5mm"),
                   Parameter('p10', type=Type.STRING,
                             doc="Text color string in RGB model. Default is black"),
                   Parameter('p11', type=Type.INT32_T,
                             doc="?LABELBOUND    - Edge bound.  0 - No"),
                   Parameter('p12', type=Type.INT32_T,
                             doc=":def:`STK_AXIS`")
               ]),

        Method('SetLineParm_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Set line parameter (of Y Chan) in :class:`STK` object",
               notes="See :class:`MSTK` for detailed description of all function parameters",
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T,
                             doc="Line symb")
               ]),

        Method('SetProfile_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Set profile parameters in :class:`STK` object",
               notes="See :class:`MSTK` for detailed description of all function parameters",
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T,
                             doc="Profile line type.    1 - solid (default)"),
                   Parameter('p3', type=Type.DOUBLE,
                             doc="Patterned line pitch in mm. Default is 10 mm"),
                   Parameter('p4', type=Type.DOUBLE,
                             doc="Line thickness in mm. Default is 0.05mm"),
                   Parameter('p5', type=Type.STRING,
                             doc="Color string in RGB model. Default is black"),
                   Parameter('p6', type=Type.INT32_T,
                             doc="Wrap option"),
                   Parameter('p7', type=Type.INT32_T,
                             doc="Clip option"),
                   Parameter('p8', type=Type.INT32_T,
                             doc="Plot smoothed polyline."),
                   Parameter('p9', type="VV",
                             doc="Integers starting from 0 indicating windows in :class:`VA` channel to draw :class:`VV` type of INT (integer)"),
                   Parameter('p10', type=Type.STRING,
                             doc="Characters string to label profiles"),
                   Parameter('p11', type=Type.INT32_T,
                             doc="Reference location to draw label."),
                   Parameter('p12', type=Type.STRING,
                             doc="Font to use to draw profile labels. Default is use 'default' font set in Montaj"),
                   Parameter('p13', type=Type.DOUBLE,
                             doc="Text size in mm to draw profile labels. Default is 5mm"),
                   Parameter('p14', type=Type.STRING,
                             doc="Text color string in RGB model. Default is black"),
                   Parameter('p15', type=Type.INT32_T,
                             doc="Include :class:`VA` column numbers as part of the profile label 0 - no, 1 - yes")
               ]),

        Method('SetProfileEx_STK', module='geogxx', version='5.0.3',
               availability=Availability.LICENSED, 
               doc="Set profile parameters in :class:`STK` object (added Break on dummy option)",
               notes="See :class:`MSTK` for detailed description of all function parameters",
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T,
                             doc="Profile line type.    1 - solid (default)"),
                   Parameter('p3', type=Type.DOUBLE,
                             doc="Patterned line pitch in mm. Default is 10 mm"),
                   Parameter('p4', type=Type.DOUBLE,
                             doc="Line thickness in mm. Default is 0.05mm"),
                   Parameter('p5', type=Type.STRING,
                             doc="Color string in RGB model. Default is black"),
                   Parameter('p6', type=Type.INT32_T,
                             doc="Break on dummy option"),
                   Parameter('p7', type=Type.INT32_T,
                             doc="Wrap option"),
                   Parameter('p8', type=Type.INT32_T,
                             doc="Clip option"),
                   Parameter('p9', type=Type.INT32_T,
                             doc="Plot smoothed polyline."),
                   Parameter('p10', type="VV",
                             doc="Integers starting from 0 indicating windows in :class:`VA` channel to draw :class:`VV` type of INT (integer)"),
                   Parameter('p11', type=Type.STRING,
                             doc="Characters string to label profiles"),
                   Parameter('p12', type=Type.INT32_T,
                             doc="Reference location to draw label."),
                   Parameter('p13', type=Type.STRING,
                             doc="Font to use to draw profile labels. Default is use 'default' font set in Montaj"),
                   Parameter('p14', type=Type.DOUBLE,
                             doc="Text size in mm to draw profile labels. Default is 5mm"),
                   Parameter('p15', type=Type.STRING,
                             doc="Text color string in RGB model. Default is black"),
                   Parameter('p16', type=Type.INT32_T,
                             doc="Include :class:`VA` column numbers as part of the profile label 0 - no, 1 - yes")
               ]),

        Method('SetSymbParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Set parameters in :class:`STK` object relating drawing symbols",
               notes="See :class:`MSTK` for detailed description of all function parameters",
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.STRING,
                             doc="Font to use to draw symbols. Default is use 'symbols.gfn' font"),
                   Parameter('p3', type=Type.DOUBLE,
                             doc="Symbol size in mm. Default is 5mm"),
                   Parameter('p4', type=Type.STRING,
                             doc="Edge color string in RGB model. Default is black"),
                   Parameter('p5', type=Type.STRING,
                             doc="Fill color string in RGB model. Default is black"),
                   Parameter('p6', type=Type.INT32_T,
                             doc="Wrap option"),
                   Parameter('p7', type=Type.INT32_T,
                             doc="Clip option"),
                   Parameter('p8', type=Type.DOUBLE,
                             doc="Y location to draw symbols. Default is to use the data from Y channel"),
                   Parameter('p9', type=Type.INT32_T,
                             doc="Number of symbols levels"),
                   Parameter('p10', type="VV",
                             doc="Y values to define data ranges for each symbol types Type of REAL"),
                   Parameter('p11', type="VV",
                             doc="Symbol numbers (given in the symbol font) to draw Type of INT"),
                   Parameter('p12', type=Type.INT32_T,
                             doc="Draw symbols ID (1) or not (0)"),
                   Parameter('p13', type=Type.STRING,
                             doc="Font to use to draw symbol ID (A,B,C...). Default is use 'default'"),
                   Parameter('p14', type=Type.DOUBLE,
                             doc="Text size in mm to draw profile labels. Default is 5mm"),
                   Parameter('p15', type=Type.STRING,
                             doc="Text color string in RGB model. Default is black")
               ]),

        Method('SetTitleParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Set parameters in :class:`STK` object relating X/Y axis titles",
               notes="""
               See :class:`MSTK` for detailed description of all function parameters
               ? mark in the note represent either X and Y
               """,
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.STRING,
                             doc="Title for bottom X axis/left Y axis. Default is no title."),
                   Parameter('p3', type=Type.STRING,
                             doc="Title for top X axis/right Y axis. Default is no title."),
                   Parameter('p4', type=Type.INT32_T,
                             doc="Bottom/Left axis title orientation."),
                   Parameter('p5', type=Type.DOUBLE,
                             doc="X location to draw bottom/left axis title"),
                   Parameter('p6', type=Type.DOUBLE,
                             doc="Y location to draw bottom/left axis title"),
                   Parameter('p7', type=Type.INT32_T,
                             doc="Top/Right axis title orientation."),
                   Parameter('p8', type=Type.DOUBLE,
                             doc="X location to draw top/right axis title"),
                   Parameter('p9', type=Type.DOUBLE,
                             doc="Y location to draw top/right axis title"),
                   Parameter('p10', type=Type.STRING,
                             doc="Font to draw titles. Default is use 'default' font set in Montaj"),
                   Parameter('p11', type=Type.DOUBLE,
                             doc="Text size in mm to draw titles. Default is 5mm"),
                   Parameter('p12', type=Type.STRING,
                             doc="Text color string in RGB model. Default is black"),
                   Parameter('p13', type=Type.INT32_T,
                             doc=":def:`STK_AXIS`")
               ]),

        Method('SetTransParms_STK', module='geogxx', version='5.0.0',
               availability=Availability.LICENSED, 
               doc="Set transformation parameters in :class:`STK` object",
               notes="""
               See above full description of each parameters
               :class:`VV`'s for X channel transformation can be NULL if the
               transformation is log or loglinear. The same for Y channel.
               See :class:`MSTK` for detailed description of all function parameters
               """,
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T,
                             doc="Type of transformation for horizontal axis"),
                   Parameter('p3', type=Type.DOUBLE,
                             doc="Minimum value to apply logarithmic"),
                   Parameter('p4', type=Type.INT32_T,
                             doc="future use"),
                   Parameter('p5', type=Type.INT32_T,
                             doc="future use"),
                   Parameter('p6', type=Type.INT32_T,
                             doc="Type of scaling for vertical axis"),
                   Parameter('p7', type=Type.DOUBLE,
                             doc="Minimum value to apply logarithmic"),
                   Parameter('p8', type=Type.INT32_T,
                             doc="future use"),
                   Parameter('p9', type=Type.INT32_T,
                             doc="future use")
               ]),

        Method('SetVAIndexStart_STK', module='geogxx', version='6.0.1',
               availability=Availability.LICENSED, 
               doc="Start array profile index labels at 0 or 1.",
               notes="""
               By default, the index labels for array channel profiles
               begin at 0. Use this function to start them at either 0
               or 1.
               """,
               return_type=Type.VOID,
               parameters = [
                   Parameter('p1', type="STK",
                             doc=":class:`STK` handle"),
                   Parameter('p2', type=Type.INT32_T,
                             doc="Starting index (0 or 1)")
               ])
    ]
}

